name: Package Application with Pyinstaller

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Script
      run: ./linux_setup.sh

    - name: Python requisite installs
      run: pip3 install -r requirements.txt pyinstaller

    - name: App creation
      run: python3 -m PyInstaller -yF --hidden-import Hamlib rflh.py

    - name: Test App
      run: cp rotor.conf dist/ && chmod +x ./dist/rflh && ./dist/rflh 145 -d

    - uses: actions/upload-artifact@v2
      with:
        name: rflh
        path: dist/rflh

