name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Python requisite installs
      run: pip3 install -r requirements.txt pyinstaller

    - name: Hamlib-python install
      run: sudo apt install python3-libhamlib2 libhamlib-utils libhamlib2

    - name: App creation
      run: python3 -m PyInstaller -yF --hidden-import Hamlib rflh.py

    - name: Test App
      run: cp rotor.conf dist/ && chmod +x ./dist/rflh && ./dist/rflh 145 -d

    - uses: actions/upload-artifact@v2
      with:
        name: rflh
        path: dist/rflh

